package resources;
import java.awt.image.BufferedImage;
import java.util.ArrayList;


public class Resources {
		public static final byte TILE = 0;
		public static final byte WALL = 1;
		public static final byte WATER = 2;
		public static final byte DIRT  = 3;
		public static final byte TREE = 4;
	    public static final byte STONE = 5;
	    public static final byte GRASS = 6;
	    public static final byte PLAYER = 7;   
	    public static final byte PLAYER_2 = 8;
	    public static final byte PLAYER_BACK = 9;
	    public static final byte PLAYER_BACK_2 = 10;
	    public static final byte PLAYER_LEFT = 11;
	    public static final byte PLAYER_LEFT_2 = 12;
	    public static final byte PLAYER_RIGHT = 13;
	    public static final byte PLAYER_RIGHT_2 = 14;
	    public static final byte AD = 15;
	    public static final byte AD_2 = 16;
	    public static final byte BULLET = 17;
	    public static final byte MISSILE = 18;
	    public static final byte MONSTER = 19;
	    public static final byte MONSTER_2 = 20;
	    public static final byte MONSTER_ATTACK = 21;
	    public static final byte GHOST = 22;
	    public static final byte GHOST_2 = 23;
	    public static final byte GHOST_ATTACK = 24;
	    public static final byte GHOST_INVISIBLE = 25;
	    public static final byte GHOST_VISIBLE_2 = 26;
	    public static final byte ITEM = 27;
	    public static final byte OBSTACLE = 28;
	    public static final byte OBSTACLE_2 = 29;
	    public static final byte BACKGROUND = 30;
	    public static final byte PLAYER_ICE = 31;
	    public static final byte F_MONSTER = 32;
	    public static final byte F_MONSTER_2 = 33;
	    public static final byte Q = 34;
	    public static final byte R = 35;  
	    public static final byte BLOOD = 36;
	    public static final byte DARK = 37;
	    public static final byte HEART = 38;
	    public static final byte MANA = 39;
	    public static final byte ARMOR = 40;
	    public static final byte ULTI = 41;
	    public static final byte HEARTB = 42;
	    public static final byte MANAB = 43;
	    public static final byte ARMORB = 44;
	    public static final byte ULTIB = 45;    
	    public static final byte BUTTON_1 = 46;
	    public static final byte BUTTON = 47;
	    public static final byte UFO = 48;
	    public static final byte PLANET = 49;
	    public static final byte UNIVERSE = 50;
	    public static final byte WALL1 = 51;
	    public static final byte WALL2 = 52;
	    public static final byte WALL3 = 53;
	    public static final byte WALL4 = 54;
	    public static final byte WALL5 = 55;
	    public static final byte WALL6 = 56;
	    public static final byte WALL7 = 57;
	    public static final byte WALL8 = 58;
	    public static final byte WALL9 = 59;
	    public static final byte WALL10 = 60;
	    public static final byte WALL11 = 61;
	    public static final byte WALL12 = 62;
	    public static final byte WALL13 = 63;
	    public static final byte WALL14 = 64;
	    public static final byte WALL15 = 65;
	    public static final byte WALL16 = 66;
	    public static final byte WALL17 = 67;
	    public static final byte WALL18 = 68;
	    public static final byte WALL19 = 69;
	    public static final byte WALL20 = 70;
	    public static final byte WALL21 = 71;
	    public static final byte BLOOD_FALL = 72;
	    public static ArrayList<BufferedImage> TEXTURES = new ArrayList<>();

	}

